### PR TITLE
add apel-pkg.el

### PR DESCRIPTION
**Pull request by egh**

### CODE REVIEW

**Comment by egh** [comment]
This file is necessary to include version and a description in a MELPA package.

**Comment by ikazuhiro** [comment]
In `apel-pkg.el`, is it possible to get version number from `apel-ver.el` by a below code (or something else)?

``` lisp
(progn
  (load "apel-ver.el")
  (product-version-as-string
   (product-find 'apel-ver)))
```

**Comment by egh** [comment]
According to the documentation `apel-pkg.el` must "contain a single Lisp form, consisting of a call to the function define-package"

https://www.gnu.org/software/emacs/manual/html_node/elisp/Multi_002dfile-Packages.html#Multi_002dfile-Packages

so I don't think we can do this.

**Comment by ikazuhiro** [comment]
I think the below content "contain a single Lisp form, consisting of a call to the function define-package".

``` lisp
(define-package
  "apel"
  (progn
    (load "apel-ver.el")
    (product-version-as-string
     (product-find 'apel-ver)))
  "APEL (A Portable Emacs Library) provides support for portable Emacs Lisp programs")
```

How do you think?  Do arguments for `define-package` have to be constant?

**Comment by egh** [comment]
`package.el` uses `cl-defstruct` to load the `package-define` and this will not work.

MELPA, in any case, rewrites the version to a datestamp, see: http://stackoverflow.com/questions/17497548/why-are-the-melpa-emacs-lisp-repository-version-numbers-so-high

Unfortunately I don't really see a way around hard-coding the version number in `apel-pkg.el` if we want to make APEL an emacs package.

**Comment by ikazuhiro** [comment]
Thank you for the comment.  I merged this pull request.  But I still want to avoid hard-coding the version number in `apel-pkg.el`.  If you have more information in the future, please let me know.

**Comment by egh** [comment]
Thanks, Kazuhiro. I will keep you updated.

**Pull request merged**
